version: "3.8"
services: 
  app:
    build: ./app/
    image: event-planner-api:latest
    container_name: event-planner-api
    restart: unless-stopped
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app
    networks:
      - event-planner-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  web:
    image: nginx:latest
    container_name: event-planner-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - event-planner-network
  rabbitmq:
    image: rabbitmq:latest
    container_name: event-planner-rabbitmq
    restart: always #unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  database:
    image: postgres:latest
    container_name: event-planner-postgres
    restart: unless-stopped 
    env_file:
    - ./app/.env
    volumes:
      - postgres-data:/var/lib/postgresql
  #    - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
  rabbitmq-data:  


networks:
  event-planner-network:
    name: event-planner-network
    driver: bridge
